services:
  # PHP-FPMコンテナ
  php:
    build: ./php
    container_name: php-container
    volumes:
      - ./php:/var/www/html
    networks:
      - my-network

  # MySQLコンテナ
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  # Nginxコンテナ
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - php
      - mysql

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
